apiVersion: v1
kind: Service
metadata:
  name: aerospike-2
  namespace: aerospike-cluster-1
  labels:
      app: aerospike-server
spec:
  type: ClusterIP
  externalIPs:
    - 192.168.110.115
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: def-2
  selector:
    statefulset.kubernetes.io/pod-name: aerospike-1
